apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole
  labels:
    nfs: pihole
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /volume1/k8sNFS/pihole
    server: 192.168.1.219